////////////////////////////////////
// 					GAME OF THRONES 				
////////////////////////////////////
CommandSet BaratheonStannisCommandSet
	1	 = Command_ToggleStance
	2	 = Command_StannisFakeLeadershipButton
	3	 = Command_SpecialAbilityStannisRoyalFleet
	4	 = Command_SpecialAbilityStannisProvenCommander
	5	 = Command_SpecialAbilityStannisLightbringer
	6	 = Command_SpecialAbilityStannisOnlyForward
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
	19 = Command_ToggleBeregondWeapon
End