////////////////////////////////////
// 					GAME OF THRONES 				
////////////////////////////////////
CommandSet BaratheonStannisCommandSet
	1	 = Command_ToggleStance
	2	 = Command_StannisFakeLeadershipButton
	3	 = Command_SpecialAbilityStannisRoyalFleet
	4	 = Command_SpecialAbilityStannisProvenCommander
	5	 = Command_SpecialAbilityStannisLightbringer
	6	 = Command_SpecialAbilityStannisOnlyForward
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
	19 = Command_ToggleBeregondWeapon
End

CommandSet BaratheonDavosCommandSet
	1	 = Command_ToggleStance
	2	 = Command_DavosStannisBonus
	3	 = Command_SpecialAbilityDavosOnionBarrels
	4	 = Command_SpecialAbilityDavosHonestAccounting
	5	 = Command_Davos_SpecialAbilityTeleportLevel2
	6	 = Command_DavosUpjumpedSmuggler
	7  = Command_ToggleBeregondWeapon
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel1
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel1
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel3
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel3
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel5
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel5
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel8
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel8
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel1
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel1
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel3
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel3
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel5
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel5
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel8
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel8
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End