////////////////////////////////////
// 					GAME OF THRONES 				
////////////////////////////////////
CommandSet TestGollumCommandSet
	1	= Command_ToggleStance
	2 = Command_SpecialAbilityTestGollumVision
	3 = Command_SpecialAbilitySilverHostSummon
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonStannisCommandSet
	1	 = Command_ToggleStance
	2	 = Command_StannisFakeLeadershipButton
	3	 = Command_SpecialAbilityStannisRoyalFleet
	4	 = Command_SpecialAbilityStannisProvenCommander
	5	 = Command_SpecialAbilityStannisLightbringer
	6	 = Command_SpecialAbilityStannisOnlyForward
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
	19 = Command_ToggleBeregondWeapon
End

CommandSet MelisandreCommandSet
	1  = Command_ToggleStance
	2  = Command_SpecialPowerMelisandreLvl3
	3  = Command_SpecialAbilityMelisandreHealingFire
	4  = Command_SpecialAbilityTheNightIsDarkAndFullOfTerrors
	5  = Command_SpecialAbilityMelisandreDeadlySeduction
	6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet MelisandreCommandSet_Lvl3
	1  = Command_ToggleStance
	2  = Command_SpecialPowerMelisandreLvl6
	3  = Command_SpecialAbilityMelisandreHealingFire
	4  = Command_SpecialAbilityTheNightIsDarkAndFullOfTerrors
	5  = Command_SpecialAbilityMelisandreDeadlySeduction
	6  = Command_SpecialAbilityMelisandreShadowbinder	
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet MelisandreCommandSet_Lvl6
	1  = Command_ToggleStance
	2  = Command_SpecialPowerMelisandreLvl10
	3  = Command_SpecialAbilityMelisandreHealingFire
	4  = Command_SpecialAbilityTheNightIsDarkAndFullOfTerrors
	5  = Command_SpecialAbilityMelisandreDeadlySeduction
	6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet MelisandreCommandSet_Lvl10
	1  = Command_ToggleStance
	2  = Command_SpecialPowerMelisandreLvl10Final
	3  = Command_SpecialAbilityMelisandreHealingFire
	4  = Command_SpecialAbilityTheNightIsDarkAndFullOfTerrors
	5  = Command_SpecialAbilityMelisandreDeadlySeduction
	6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonDavosCommandSet
	1	 = Command_ToggleStance
	2	 = Command_DavosStannisBonus
	3	 = Command_SpecialAbilityDavosOnionBarrels
	4	 = Command_SpecialAbilityDavosHonestAccounting
	5	 = Command_Davos_SpecialAbilityTeleportLevel2
	6	 = Command_DavosUpjumpedSmuggler
	7  = Command_ToggleBeregondWeapon
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel1
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel1
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel3
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel3
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel5
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel5
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonGendryCommandSetLevel8
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfFleaBottom
	3	 = Command_SpecialAbilityGendrySkilledSmithLevel8
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel1
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel1
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel3
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel3
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel5
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel5
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonLordGendryCommandSetLevel8
	1	 = Command_ToggleStance
	2	 = Command_SpecialAbilityGendryOfStormsEnd
	3	 = Command_SpecialAbilityGendryLeapLevel8
	4	 = Command_SpecialAbilityGendryStrongSeed
	5	 = Command_SpecialAbilityGendryTheBull
	6	 = Command_SpecialAbilityGendryKnightOfTheHollowHill
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneFortressCommandSet
	InitialVisible = 7
	//Main Menu
	1	= Command_ConstructBaratheonPorter
	2	= Command_SelectRevivablesDragonstoneFortress
	3 = Command_SelectBaratheonDavosUpgrades
	4	= Command_SelectUpgradesDragonstoneFortress
	5 = Command_SelectBaratheonMelisandreUpgrades
	7	= Command_FireDragonstoneFortressSmokeAndBrimstone
	6	= Command_Sell
	//Upgrades Menu
	12 = Command_PurchaseUpgradeDragonstoneFortressBaratheonBanners
	13 = Command_PurchaseUpgradeDragonstoneFortressLavaMoat
	14 = Command_PurchaseUpgradeDragonstoneFortressSmokeAndBrimstone
	;15	= Command_PurchaseUpgradeMordorFortressFireArrows // Will be Dragons for the Targaryens
	15 = Command_PurchaseUpgradeDragonstoneFortressValyrianSorcery
	16 = Command_PurchaseUpgradeDragonstoneFortressStoneDrum
	17 = Command_RadialBack
	//Decisions Upgrades
	18 = Command_SelectBaratheonLawfulSon
	19 = Command_SelectBaratheonDavosUpgrade2
	20 = Command_RadialBack
	21 = Command_SelectBaratheonKingsBloodPower
	22 = Command_SelectBaratheonMelisandreUpgrade2
	23 = Command_RadialBack
	//Hero Menu
	24 = Command_RingHeroReviveSlot
	25 = Command_CreateAHeroReviveSlot		// Note we also need an extra slot for the Create A Hero
	26 = Command_GenericReviveSlot1
	27 = Command_GenericReviveSlot2
	28 = Command_GenericReviveSlot3
	29 = Command_GenericReviveSlot4
	30 = Command_GenericReviveSlot5
	31 = Command_GenericReviveSlot6
	32 = Command_RadialBack
End

CommandSet ShireenCommandSet
	1  = Command_ToggleStance
	2  = Command_SpecialPowerShireenLvl3
	3  = Command_SpecialPowerShireenGoodAndKind
	4  = Command_SpecialPowerShireenGlowOfTheGreyscale
	5  = Command_SpecialAbilityShireenLearnedChild
	;6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet ShireenCommandSet_Lvl3
	1  = Command_ToggleStance
	2  = Command_SpecialPowerShireenLvl6
	3  = Command_SpecialPowerShireenGoodAndKind
	4  = Command_SpecialPowerShireenGlowOfTheGreyscale
	5  = Command_SpecialAbilityShireenLearnedChild
	;6  = Command_SpecialAbilityMelisandreShadowbinder	
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet ShireenCommandSet_Lvl6
	1  = Command_ToggleStance
	2  = Command_SpecialPowerShireenLvl10
	3  = Command_SpecialPowerShireenGoodAndKind
	4  = Command_SpecialPowerShireenGlowOfTheGreyscale
	5  = Command_SpecialAbilityShireenLearnedChild
	;6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet ShireenCommandSet_Lvl10
	1  = Command_ToggleStance
	2  = Command_SpecialPowerShireenLvl10Final
	3  = Command_SpecialPowerShireenGoodAndKind
	4  = Command_SpecialPowerShireenGlowOfTheGreyscale
	5  = Command_SpecialAbilityShireenLearnedChild
	;6  = Command_SpecialAbilityMelisandreShadowbinder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonSalladhorSaanCommandSet
	1	 = Command_ToggleStance
	2	 = Command_SalladhorSaanFakeLeadership
	3	 = Command_SpecialAbilityButAGoodFriend
	4	 = Command_SpecialAbilityDesireOfPlunder
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
	19 = Command_ToggleBeregondWeapon
End

CommandSet DrogonDragonCommandSet
	1 = Command_ToggleStance
	2 = Command_DrogonStun
	3 = Command_DrogonFlamestrike
	4 = Command_DrogonsWrath
	5 = Command_DrogonWingBlast
	6 = Command_DrogonDracarys
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet RhaegalDragonCommandSet
	1 = Command_ToggleStance
	2 = Command_DrogonStun
	3 = Command_DrogonFlamestrike
	4 = Command_DrogonsWrath
	5 = Command_RhaegalWingBlast
	6 = Command_RhaegalDracarys
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet ViserionDragonCommandSet
	1 = Command_ToggleStance
	2 = Command_DrogonStun
	3 = Command_DrogonFlamestrike
	4 = Command_DrogonsWrath
	5 = Command_ViserionWingBlast
	6 = Command_ViserionDracarys
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonPorterCommandSet
	1 = Command_EvilStop
	2 = Command_PorterExtinguishFire
	3 = Command_PorterConstructMordorSlaughterHouse
	4 = Command_PorterConstructMordorLumberMill
	5	= Command_PorterConstructMordorArmory
	6 = Command_PorterConstructBaratheonDragonstoneBarracks
	7 = Command_PorterConstructMordorHaradrimPalace
	8 = Command_PorterConstructMordorTrollCage
	9 = Command_PorterConstructMordorSiegeWorks
	10 = Command_PorterconstructMordorBattleTower
	11 = Command_PorterConstructMordorFortress
End

CommandSet BaratheonBarracksCommandSet
	1 = Command_ConstructBaratheonCorsairOfLysHorde
	2 = Command_ConstructBaratheonDragonstoneSoldierHorde
	3 = Command_ConstructBaratheonDragonstonePikemanHorde
	4 = Command_ConstructBaratheonDragonstoneArcherHorde
	5 = Command_ConstructBaratheonDragonstoneKnightHorde
	7 = Command_UpgradeBaratheonDragonstoneBarracksLevel2
	6	= Command_Sell
End

CommandSet BaratheonBarracksCommandSetLvl2
	1 = Command_ConstructBaratheonCorsairOfLysHorde
	2 = Command_ConstructBaratheonDragonstoneSoldierHorde
	3 = Command_ConstructBaratheonDragonstonePikemanHorde
	4 = Command_ConstructBaratheonDragonstoneArcherHorde
	5 = Command_ConstructBaratheonDragonstoneKnightHorde
	7 = Command_UpgradeBaratheonDragonstoneBarracksLevel3
	6	= Command_Sell
End

CommandSet BaratheonBarracksCommandSetLvl3
	1 = Command_ConstructBaratheonCorsairOfLysHorde
	2 = Command_ConstructBaratheonDragonstoneSoldierHorde
	3 = Command_ConstructBaratheonDragonstonePikemanHorde
	4 = Command_ConstructBaratheonDragonstoneArcherHorde
	5 = Command_ConstructBaratheonDragonstoneKnightHorde
	6	= Command_Sell
End

CommandSet BaratheonArmoryCommandSetLevel1
	1 = Command_PurchaseTechnologyBaratheonBasicTraining
	2	= Command_PurchaseTechnologyBaratheonForgedBlades
	3	= Command_PurchaseTechnologyBaratheonHeavyArmor
	4	= Command_PurchaseTechnologyBaratheonFireArrows
	5 = Command_UpgradeBaratheonDragonstoneFoundryLevel2
	6 = Command_Sell
End

CommandSet BaratheonArmoryCommandSetLevel2
	1 = Command_PurchaseTechnologyBaratheonBasicTraining
	2	= Command_PurchaseTechnologyBaratheonForgedBlades
	3	= Command_PurchaseTechnologyBaratheonHeavyArmor
	4	= Command_PurchaseTechnologyBaratheonFireArrows
	5 = Command_UpgradeBaratheonDragonstoneFoundryLevel3
	6 = Command_Sell
End

CommandSet BaratheonArmoryCommandSetLevel3
	1 = Command_PurchaseTechnologyBaratheonBasicTraining
	2	= Command_PurchaseTechnologyBaratheonForgedBlades
	3	= Command_PurchaseTechnologyBaratheonHeavyArmor
	4	= Command_PurchaseTechnologyBaratheonFireArrows
	6 = Command_Sell
End

CommandSet DragonstoneFighterHordeCommandSet
	1 = Command_ToggleStance
	2	= Command_ToggleFormationGondorFighterElite
	3	= Command_SpecialAbilityAppealToTheLordOfLightDamage
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5	= Command_PurchaseUpgradeBaratheonForgedBlades
	6	= Command_PurchaseUpgradeBaratheonBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneFighterHordeCommandSet_Lvl2
	1 = Command_ToggleStance
	2	= Command_ToggleFormationGondorFighterElite
	3	= Command_SpecialAbilityAppealToTheLordOfLightDamage
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5	= Command_PurchaseUpgradeBaratheonForgedBlades
	6	= Command_SpecialAbilityBaratheonFaithfulResolve
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstonePikemanHordeCommandSet
	1 = Command_ToggleStance
	2 = Command_RivendellSentryPorcupineFormation
	3	= Command_SpecialAbilityAppealToTheLordOfLightArmor
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5 = Command_PurchaseUpgradeBaratheonForgedBlades
	6 = Command_PurchaseUpgradeBaratheonBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstonePikemanHordeCommandSet_Lvl2
	1 = Command_ToggleStance
	2 = Command_RivendellSentryPorcupineFormation
	3	= Command_SpecialAbilityAppealToTheLordOfLightArmor
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5 = Command_PurchaseUpgradeBaratheonForgedBlades
	6 = Command_SpecialAbilityBaratheonFaithfulResolve
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneArcherHordeCommandSet
	1 = Command_ToggleStance
	2	= Command_ArcherBombard
	3	= Command_SpecialAbilityAppealToTheLordOfLightRange
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5 = Command_PurchaseUpgradeBaratheonFireArrows
	6 = Command_PurchaseUpgradeBaratheonBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneArcherHordeCommandSet_Lvl2
	1 = Command_ToggleStance
	2	= Command_ArcherBombard
	3	= Command_SpecialAbilityAppealToTheLordOfLightRange
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5 = Command_PurchaseUpgradeBaratheonFireArrows
	6 = Command_SpecialAbilityBaratheonFaithfulResolve
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneKnightHordeCommandSet
	1 = Command_ToggleStance
	2 = Command_ToggleFormationDunedainOutriders
	3 = Command_SpecialAbilityAppealToTheLordOfLightTrample
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5	= Command_PurchaseUpgradeBaratheonForgedBlades
	6	= Command_PurchaseUpgradeBaratheonBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet DragonstoneKnightHordeCommandSet_Lvl2
	1 = Command_ToggleStance
	2 = Command_ToggleFormationDunedainOutriders
	3 = Command_SpecialAbilityAppealToTheLordOfLightTrample
	4 = Command_PurchaseUpgradeBaratheonHeavyArmor
	5	= Command_PurchaseUpgradeBaratheonForgedBlades
	6	= Command_SpecialAbilityBaratheonFaithfulResolve
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonCorsairOfLysHordeCommandSet
	1	= Command_ToggleStance
	3	= Command_ToggleCorsairWeaponHarad
	4	= Command_SpecialAbilityCorsairsOfLysCoastalRaiders
	6	= Command_PurchaseUpgradeBaratheonBasicTrainingCorsairsOfLys
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End

CommandSet BaratheonCorsairOfLysHordeCommandSetFireBomb
	1	= Command_ToggleStance
	2	= Command_ArcherBombard
	3	= Command_ToggleCorsairWeaponHarad
	4	= Command_SpecialAbilityCorsairsOfLysCoastalRaiders
	6	= Command_PurchaseUpgradeBaratheonBasicTrainingCorsairsOfLys
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16 = Command_SetStanceBattle
	17 = Command_SetStanceAggressive
	18 = Command_SetStanceHoldGround
End