// @format
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ASOIAF LEVELS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ExperienceLevel	Tier7HeroesLevel1
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_7_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel2
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel3
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel4
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel5
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel6
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel7
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel8
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel9
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier7HeroesLevel10
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel1
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_6_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel2
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel3
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel4
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel5
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel6
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel7
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel8
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel9
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier6HeroesLevel10
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel1
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_5_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel2
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel3
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel4
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel5
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel6
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel7
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel8
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel9
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier5HeroesLevel10
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel1
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_4_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel2
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel3
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel4
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel5
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel6
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel7
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel8
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel9
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier4HeroesLevel10
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel1
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_3_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel2
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel3
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel4
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel5
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel6
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel7
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_3_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel8
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel9
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier3HeroesLevel10
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel1
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_2_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel2
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel3
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel4
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel5
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel6
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel7
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel8
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel9
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier2HeroesLevel10
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel1
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_1_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel2
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel3
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel4
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel5
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel6
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel7
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel8
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel9
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Tier1HeroesLevel10
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel1
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 1
	ExperienceAward		 = ARWEN_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel2
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 1000000
	ExperienceAward		 = ARWEN_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel3
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 2000000
	ExperienceAward		 = ARWEN_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	AttributeModifiers = HeroLevelUpDamage2
	Upgrades					 = Upgrade_ObjectLevel3
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel4
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 3000000 ;ARWEN_LVL4_EXP_NEEDED
	ExperienceAward		 = ARWEN_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	AttributeModifiers = HeroLevelUpDamage3
	Upgrades					 = Upgrade_ObjectLevel4
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel5
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 4000000
	ExperienceAward		 = ARWEN_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel6
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 5000000
	ExperienceAward		 = ARWEN_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	AttributeModifiers = HeroLevelUpDamage5
	Upgrades					 = Upgrade_ObjectLevel6
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel7
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 6000000
	ExperienceAward		 = ARWEN_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel8
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 7000000
	ExperienceAward		 = ARWEN_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	AttributeModifiers = HeroLevelUpDamage7
	Upgrades					 = Upgrade_ObjectLevel8
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel9
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 8000000
	ExperienceAward		 = ARWEN_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	PurchaseableLevel10
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 9000000
	ExperienceAward		 = ARWEN_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	Upgrades					 = Upgrade_ObjectLevel10
	AttributeModifiers = HeroLevelUpDamage9
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	MiniHordeLevel1_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_1
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_1
	InformUpdateModule = Yes
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	SelectionDecal
		Texture		 =	decal_I_level1
		Texture2	 =	decal_evil_CO
		Style			 =	SHADOW_MERGE_DECAL
		OpacityMin =	80%
		OpacityMax =	100%
		MinRadius	 =	HORDE_DECAL_MIN_RADIUS
		MaxRadius	 =	200
		MaxSelectedUnits =	40
	End
END

ExperienceLevel	MiniHordeLevel2_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_2
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_2
	AttributeModifiers = MiniHordeBonusRank2
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl2 Upgrade_ObjectLevel2
	Rank							 = 2
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level2
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel3_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_3
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_3
	AttributeModifiers = MiniHordeBonusRank3
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl3
	Rank							 = 3
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level3
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel4_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_4
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_4
	AttributeModifiers = MiniHordeBonusRank4
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl4
	Rank							 = 4
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel5_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_5
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_5
	AttributeModifiers = MiniHordeBonusRank5
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl5
	Rank							 = 5
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor					  =	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel6_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_6
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_6
	AttributeModifiers = MiniHordeBonusRank6
	InformUpdateModule = Yes
	Rank							 = 6
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel7_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_7
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_7
	AttributeModifiers = MiniHordeBonusRank7
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl7
	Rank							 = 7
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		= 3000
	LevelUpTintSustainColorTime =	500
	EmotionType									= CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel8_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_8
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_8
	AttributeModifiers = MiniHordeBonusRank8
	InformUpdateModule = Yes
	Rank							 = 8
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel9_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_9
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_9
	AttributeModifiers = MiniHordeBonusRank9
	InformUpdateModule = Yes
	Rank							 = 9
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	MiniHordeLevel10_GOT
	TargetNames				 = MINI_HORDE_GOT
	RequiredExperience = AOTR_EXPERIENCE_REQUIRED_MINI_HORDE_10
	ExperienceAward		 = EXPERIENCE_AWARD_MINI_HORDE_10
	AttributeModifiers = MiniHordeBonusRank10
	InformUpdateModule = Yes
	Upgrades					 = Upgrade_MiniHordeLvl10
	Rank							 = 10
	LevelUpFx					 = FX:EvilLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	EmotionType									=	CHEER
	SelectionDecal
		Texture					 = decal_I_level4
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	PorterLevel1_GOT
	TargetNames				 = PORTERS_GOT
	RequiredExperience = 1
	ExperienceAward		 = 10
	Rank							 = 1
	SelectionDecal
		Texture					 = decal_I_level1
		Texture2				 = decal_evil_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius				 = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End

ExperienceLevel	Level10Heroes
	TargetNames				 = TestGollum
	RequiredExperience = 1
	Rank		       		 = 10
	Upgrades					 = Upgrade_ObjectLevel1 Upgrade_ObjectLevel2 Upgrade_ObjectLevel3 Upgrade_ObjectLevel4 Upgrade_ObjectLevel5 Upgrade_ObjectLevel6 Upgrade_ObjectLevel7 Upgrade_ObjectLevel8 Upgrade_ObjectLevel9 Upgrade_ObjectLevel10 Upgrade_LegolasHawkStrike
	SelectionDecal
		Texture					 =	decal_hero_good
		Style						 =	SHADOW_ALPHA_DECAL
		OpacityMin			 =	50%
		OpacityMax			 =	100%
		MinRadius				 =	40
		MaxRadius				 =	200
		MaxSelectedUnits =	40
	End
END

ExperienceLevel	EliteLevel1_GOT
	TargetNames				 =	ELITE_GOT
	RequiredExperience =	EXPERIENCE_REQUIRED_GOOD_ELITE_1
	ExperienceAward		 =	EXPERIENCE_AWARD_GOOD_ELITE_1
	InformUpdateModule =	Yes
	Rank							 =	1
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	Upgrades										=	Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_G_level1
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	EliteLevel2_GOT
	TargetNames				 = ELITE_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_ELITE_2
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_ELITE_2
	AttributeModifiers = GoodEliteBonusRank2
	InformUpdateModule = Yes
	Rank							 = 2
	LevelUpFx										=	FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	Upgrades										=	Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_G_level2
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	EliteLevel3_GOT
	TargetNames				 = ELITE_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_ELITE_3
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_ELITE_3
	AttributeModifiers = GoodEliteBonusRank3
	InformUpdateModule = Yes
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	LevelUpFx					 					= FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	SelectionDecal
		Texture					 = decal_G_level3
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	EliteLevel4_GOT
	TargetNames				 = ELITE_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_ELITE_4
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_ELITE_4
	AttributeModifiers = GoodEliteBonusRank4
	InformUpdateModule = Yes
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	LevelUpFx					 					= FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	SelectionDecal
		Texture					 = decal_G_level4
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	EliteLevel5_GOT
	TargetNames				 = ELITE_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_ELITE_5
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_ELITE_5
	AttributeModifiers = GoodEliteBonusRank5
	InformUpdateModule = Yes
	Rank							 = 5
	Upgrades					 = Upgrade_ObjectLevel5
	LevelUpFx										=	FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	SelectionDecal
		Texture					 = decal_G_level4
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	Level1_GOT
	TargetNames				 = TROOPS_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_TROOP_1
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_TROOP_1
	InformUpdateModule = Yes
	Rank							 = 1
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	Upgrades										=	Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_G_level1
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	Level2_GOT
	TargetNames				 = TROOPS_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_TROOP_2
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_TROOP_2
	AttributeModifiers = GoodTroopBonusRank2
	InformUpdateModule = Yes
	Rank							 = 2
	LevelUpFx										=	FX:GoodLevelUpFX ;FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	Upgrades										=	Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_G_level2
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	Level3_GOT
	TargetNames				 = TROOPS_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_TROOP_3
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_TROOP_3
	AttributeModifiers = GoodTroopBonusRank3
	InformUpdateModule = Yes
	Rank							 = 3
	LevelUpFx					 					= FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime =	500
	Upgrades										=	Upgrade_ObjectLevel3 Upgrade_MiniHordeLvl3
	SelectionDecal
		Texture					 = decal_G_level3
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	Level4_GOT
	TargetNames				 = TROOPS_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_TROOP_4
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_TROOP_4
	AttributeModifiers = GoodTroopBonusRank4
	InformUpdateModule = Yes
	Rank							 = 4
	LevelUpFx										=	FX:GoodLevelUpFX ;FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	Upgrades										=	Upgrade_ObjectLevel4 Upgrade_MiniHordeLvl4
	SelectionDecal
		Texture					 = decal_G_level4
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END

ExperienceLevel	Level5_GOT
	TargetNames				 = TROOPS_GOT
	RequiredExperience = EXPERIENCE_REQUIRED_GOOD_TROOP_5
	ExperienceAward		 = EXPERIENCE_AWARD_GOOD_TROOP_5
	AttributeModifiers = GoodTroopBonusRank5
	InformUpdateModule = Yes
	Rank							 = 5
	LevelUpFx					 					=	FX:GoodLevelUpFX
	LevelUpTintColor						=	R:255 G:255	B:255
	LevelUpTintPreColorTime			=	500
	LevelUpTintPostColorTime		=	3000
	LevelUpTintSustainColorTime	=	500
	Upgrades										=	Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_G_level4
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40 
	End
END

ExperienceLevel	SummonedLevel1_GOT
	TargetNames				 = SUMMONED_GOT
	RequiredExperience = 1
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_G_level1
		Texture2				 = decal_good_CO
		Style						 = SHADOW_MERGE_DECAL
		OpacityMin			 = 80%
		OpacityMax			 = 100%
		MinRadius			   = HORDE_DECAL_MIN_RADIUS
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
END
