;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ASOIAF LEVELS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ExperienceLevel	Tier7HeroesLevel1
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_7_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel2
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel3
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel4
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel5
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel6
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel7
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel8
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel9
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier7HeroesLevel10
	TargetNames				 = TIER_7_HEROES
	RequiredExperience = TIER_7_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_7_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel1
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_6_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel2
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel3
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel4
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel5
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel6
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel7
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel8
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel9
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier6HeroesLevel10
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_6_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_6_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel1
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_5_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel2
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel3
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel4
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel5
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel6
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel7
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel8
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel9
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier5HeroesLevel10
	TargetNames				 = TIER_5_HEROES
	RequiredExperience = TIER_5_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_5_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel1
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_4_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel2
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel3
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel4
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel5
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel6
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel7
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel8
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel9
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier4HeroesLevel10
	TargetNames				 = TIER_4_HEROES
	RequiredExperience = TIER_4_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_4_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel1
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_3_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel2
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel3
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel4
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel5
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel6
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel7
	TargetNames				 = TIER_6_HEROES
	RequiredExperience = TIER_3_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel8
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel9
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier3HeroesLevel10
	TargetNames				 = TIER_3_HEROES
	RequiredExperience = TIER_3_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_3_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel1
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_2_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel2
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel3
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel4
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel5
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel6
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel7
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel8
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel9
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier2HeroesLevel10
	TargetNames				 = TIER_2_HEROES
	RequiredExperience = TIER_2_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_2_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel1
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = 1
	ExperienceAward		 = TIER_1_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel2
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL2_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel3
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL3_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	Upgrades					 = Upgrade_ObjectLevel3
	AttributeModifiers = HeroLevelUpDamage2
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel4
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL4_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	Upgrades					 = Upgrade_ObjectLevel4
	AttributeModifiers = HeroLevelUpDamage3
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel5
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL5_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel6
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL6_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	Upgrades					 = Upgrade_ObjectLevel6
	AttributeModifiers = HeroLevelUpDamage5
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel7
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL7_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	Upgrades					 = Upgrade_ObjectLevel7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel8
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL8_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	Upgrades					 = Upgrade_ObjectLevel8
	AttributeModifiers = HeroLevelUpDamage7
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel9
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL9_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	Upgrades					 = Upgrade_ObjectLevel9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	Tier1HeroesLevel10
	TargetNames				 = TIER_1_HEROES
	RequiredExperience = TIER_1_LVL10_EXP_NEEDED
	ExperienceAward		 = TIER_1_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	AttributeModifiers = HeroLevelUpDamage9
	Upgrades					 = Upgrade_ObjectLevel10
	SelectionDecal
		Texture					 = decal_hero_good
		Style						 = SHADOW_ALPHA_DECAL
		OpacityMin			 = 50%
		OpacityMax			 = 100%
		MinRadius				 = 40
		MaxRadius				 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel1
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 1
	ExperienceAward		 = ARWEN_LVL1_EXP_AWARD
	Rank							 = 1
	Upgrades					 = Upgrade_ObjectLevel1
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel2
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 1000000
	ExperienceAward		 = ARWEN_LVL2_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 2
	AttributeModifiers = HeroLevelUpDamage1
	Upgrades					 = Upgrade_ObjectLevel2
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel3
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 2000000
	ExperienceAward		 = ARWEN_LVL3_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 3
	AttributeModifiers = HeroLevelUpDamage2
	Upgrades					 = Upgrade_ObjectLevel3
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel4
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 3000000 ;ARWEN_LVL4_EXP_NEEDED
	ExperienceAward		 = ARWEN_LVL4_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 4
	AttributeModifiers = HeroLevelUpDamage3
	Upgrades					 = Upgrade_ObjectLevel4
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel5
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 4000000
	ExperienceAward		 = ARWEN_LVL5_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 5
	AttributeModifiers = HeroLevelUpDamage4
	Upgrades					 = Upgrade_ObjectLevel5
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel6
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 5000000
	ExperienceAward		 = ARWEN_LVL6_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 6
	AttributeModifiers = HeroLevelUpDamage5
	Upgrades					 = Upgrade_ObjectLevel6
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel7
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 6000000
	ExperienceAward		 = ARWEN_LVL7_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 7
	AttributeModifiers = HeroLevelUpDamage6
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel8
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 7000000
	ExperienceAward		 = ARWEN_LVL8_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 8
	AttributeModifiers = HeroLevelUpDamage7
	Upgrades					 = Upgrade_ObjectLevel8
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel9
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 8000000
	ExperienceAward		 = ARWEN_LVL9_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 9
	AttributeModifiers = HeroLevelUpDamage8
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End
ExperienceLevel	PurchaseableLevel10
	TargetNames				 = PURCHASEABLE_LEVELS_HEROES
	RequiredExperience = 9000000
	ExperienceAward		 = ARWEN_LVL10_EXP_AWARD
	LevelUpFx					 = FX:GoodLevelUpFX
	Rank							 = 10
	Upgrades					 = Upgrade_ObjectLevel10
	AttributeModifiers = HeroLevelUpDamage9
	SelectionDecal
		Texture		 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin = 50%
		OpacityMax = 100%
		MinRadius	 = 40
		MaxRadius	 = 200
		MaxSelectedUnits = 40
	End
End